### ISSUE TITLE
Improve code quality for EditRoom

### ISSUE THREAD

**Issue by LeeMingDe** [AY2021S1-CS2103T-W12-1/tp#126]
* Create a method called `getRoomWithRoomNumber` in `ModelManager.java` that allows you to get the room with the room number (something like what is done for patient)
* Create a method called `getRoomWithRoomNumber` in `RoomList.java` that allows you to get the room with the room number 
* Use the `hasRoom` method (like what has been done for EditPatientCommand)

**Comment by w-yeehong** [comment]
`getRoomWithRoomNumber` has been implemented in #115. Can use that for `EditRoom` too.
